# Generated by Django 4.1.5 on 2023-01-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
